import Navigation from './_components/mobile/navigation/Navigation';
import './globals.css';
import { Roboto_Mono } from 'next/font/google';
import { ThemeProvider } from './theme-provider';

const roboto_mono = Roboto_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ['latin'],
  display: "swap"
});

const navigationLinks = [
  {
    text: "Home",
    href: "/",
    iconOutline: "home-outline",
    iconSolid: "home",
    ariaLabel: "Home"
  },
  {
    text: "News",
    href: "/news",
    iconOutline: "newspaper-outline",
    iconSolid: "newspaper",
    ariaLabel: "News"
  },
  {
    text: "Statistics",
    href: "/statistics",
    iconOutline: "stats-chart-outline",
    iconSolid: "stats-chart",
    ariaLabel: "Statistics"
  },
  {
    text: "Hall of Fame",
    href: "/hall-of-fame",
    iconOutline: "trophy-outline",
    iconSolid: "trophy",
    ariaLabel: "Hall of Fame"
  }
];

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className} mt-6 mb-32 text-xs`}>
        <ThemeProvider>
          {children}
          <Navigation data={navigationLinks}/>

          <div className="fixed inset-x-0 bottom-0 bg-gradient-to-t from-white to-transparent backdrop-blur-sm h-[4%]"></div>
        </ThemeProvider>
      </body>
    </html>
  )
}